# Generated by Django 6.0.2 on 2026-04-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_status",
            field=models.CharField(
                choices=[
                    ("available", "貸出可"),
                    ("reservable", "予約可"),
                    ("borrowed", "貸出中"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="location",
            field=models.CharField(default="未設定", max_length=255),
        ),
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
