# Generated by Django 6.0.2 on 2026-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_borrow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrowed_at",
            field=models.DateField(),
        ),
    ]
