# Generated by Django 6.0.2 on 2026-04-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_borrow_borrowed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrowed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
