# Generated by Django 6.0.2 on 2026-04-13 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_borrow_borrowed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrowed_at",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
