# Generated by Django 6.0.2 on 2026-04-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "★1"), (2, "★2"), (3, "★3"), (4, "★4"), (5, "★5")]
            ),
        ),
    ]
