# Generated by Django 6.0.2 on 2026-04-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="book_status",
        ),
    ]
