# Generated by Django 6.0.2 on 2026-04-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_remove_book_book_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(),
        ),
    ]
