# Generated by Django 6.0.2 on 2026-04-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_review_unique_review_per_user_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="保管場所名")),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="location",
        ),
    ]
