# Generated by Django 6.0.2 on 2026-04-25 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_location_remove_book_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.location",
                verbose_name="保管場所",
            ),
        ),
    ]
